src/AzureIoTDemo/Models/TemperatureRead.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AzureIoTDemo.Models
{
    public class TemperatureRead
    {
        public int ID { get; set; }
        public string Place { get; set; }
        public DateTime Date { get; set; }
        public float Value { get; set; }
    }
}

src/AzureIoTDemo/Controllers/TempController.cs
using AzureIoTDemo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AzureIoTDemo.Controllers
{
    public class TempController : Controller
    {
        private TemperatureContext _context;
        public TempController(TemperatureContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var tempReads = await _context.TemperatureReads.ToListAsync();
            return View(tempReads);
        }

        // GET /Temp/Chart?place={place}
        public async Task<IActionResult> Chart(string place)
        {
            if (string.IsNullOrEmpty(place))
                return BadRequest();

            var tempReads = await _context
                .TemperatureReads
                .Where(tempRead => tempRead.Place == place)
                .ToListAsync();

            if (tempReads.Count == 0)
                return NotFound();

            return View(tempReads);
        }
    }
}

src/AzureIoTDemo/Controllers/TemperatureController.cs
using AzureIoTDemo.Data;
using AzureIoTDemo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace AzureIoTDemo.Controllers
{
    [Route("api/[controller]")]
    public class TemperatureController : Controller
    {
        private TemperatureContext _context;
        public TemperatureController(TemperatureContext context)
        {
            _context = context;
        }

        // GET api/temperature
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var tempReads = await _context
                .TemperatureReads
                .ToListAsync();

            if (tempReads.Count == 0)
                return NoContent();

            return Ok(tempReads);
        }

        // GET api/temperature/{id}
        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Get(int id)
        {
            var tempRead = await _context
                .TemperatureReads
                .FirstOrDefaultAsync(item => item.ID == id);

            if (tempRead == null)
                return NotFound();

            return Ok(tempRead);
        }

        // POST api/temperature
        [HttpPost]
        public async Task<IActionResult> Post([FromBody] TemperatureRead tempRead)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            // Because binding doesn't seem to work.
            tempRead.ID = 0;
            // Because NTP is hard.
            tempRead.Date = DateTime.Now;

            _context.Add(tempRead);
            await _context.SaveChangesAsync();

            return Ok();
        }

        // DELETE /api/temperature/{id}
        [HttpDelete]
        [Route("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var tempRead = await _context.TemperatureReads.FirstOrDefaultAsync(t => t.ID == id);

            if (tempRead == null)
                return BadRequest();

            _context
                .TemperatureReads
                .Remove(tempRead);

            await _context
                .SaveChangesAsync();

            return Ok();
        }
    }
}

src/AzureIoTDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Temperatures - AzureIoTDemo</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Temp" asp-action="Index" class="navbar-brand">AzureIoTDemo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Temp" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - AzureIoTDemo</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/AzureIoTDemo/Views/Temp/Chart.cshtml
@model IEnumerable<AzureIoTDemo.Models.TemperatureRead>

<h1 style="text-align:center">I can't make a chart, front-end is hard >.></h1>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Place)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
            </tr>
        }
    </tbody>
</table>

src/AzureIoTDemo/Views/Temp/Index.cshtml
@model IEnumerable<AzureIoTDemo.Models.TemperatureRead>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Place)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Value)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Place)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
            </tr>
        }
    </tbody>
</table>